general:
  label: 基本设置
  items:
    icp:
      name: icp
      label: ICP 备案号
      type: text
      default: ""
      placeholder: "请填写 ICP 备案号信息"
      description: "ICP 备案信息将展示在页脚中，不填不展示"
    police:
      name: police
      label: 公网备案号
      type: text
      default: ""
      placeholder: "请填写公网安备号信息"
      description: "公网安备信息将展示在页脚中，不填不展示"
    site_notice:
      name: site_notice
      label: 网站公告
      type: textarea
      placeholder: 请输入公告信息
      description: "网站公告信息，将展示在页面右侧，尽量简洁明了，不填不展示该模块"


theme:
  label: 主题相关
  items:
    theme_mode:
      name: theme_mode
      label: 主题模式
      type: select
      data-type: text
      default: user
      description: "设置博客的主题模式（缤纷/白昼/夜莺/自定义），默认为缤纷模式"
      options:
        - value: colorful
          label: 缤纷
        - value: daylight
          label: 白昼
        - value: nightingale
          label: 夜莺
        - value: custom
          label: 自定义


command:
  label: 命令相关
  items:
    help_setting:
      name: help_setting
      label: help显示
      type: text
      default: "测试版[sudo ]command[ Options...]<br/>You can use following commands:<br/><br/>cd<br/>ls<br/>cat<br/>clear<br/>help<br/><br/>Besides, there are some hidden commands, try to find them!"
      description: '自定义help命令的输出'
    ls_setting:
      name: ls_setting
      label: ls显示
      type: select
      default: "post"
      description: '自定义ls命令的输出'
      options:
        - value: "post"
          label: 文章
        # - value: "categories"
        #   label: 分类
        # - value: "tags"
        #   label: 标签